# true color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# custom binds
bind-key t split-window -l 3

# set window and pane index to 1 (0 by default)
set-option -g base-index 1
setw -g pane-base-index 1

# Colours
blue_light="#cdd6f4"
blue="#89b4fa"
yellow="#f9e2af"

# set status bar
set -g status-position top
#set -g status-left-length 70

# change active windows color
set -g status-style "bg=default,fg=${blue}"
set -g status-left "#[fg=${blue},bold]   #[fg=${blue_light},nobold]|"
set -g window-status-current-format "#[fg=${yellow},bold]  #[underscore]#I:#W"
set -g window-status-current-style "bg=default,fg=linen"
set -g window-status-format " #I:#W"

# start with predefined windows
set-option -g allow-rename off
new -s ayame -n local
neww -n hana
neww -n console
neww -n cloud
neww -n netxms
selectw -t 1
